# Generated by Django 2.0.4 on 2018-04-18 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='nombre',
            new_name='name',
        ),
    ]
