# Generated by Django 2.0.4 on 2018-04-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0004_auto_20180420_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photograpy',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
