# Generated by Django 2.0.4 on 2018-04-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0005_auto_20180420_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='photograpy',
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
